# As of 05-26, rubocop was not finding a comment based override in the source
# file, therefore created this to allow start_up_system.rb to define
# executeInEDT method.

inherit_from: ../.rubocop.yml

MethodName:
  Enabled: false
