AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - out/**/*
  - dist/**/*
  - tmp/**/*

  # See https://github.com/bbatsov/rubocop for details

Layout/SpaceBeforeFirstArg:
  AllowForAlignment: true  # Prefer to align args in multiple calls in a row

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/LineLength:
  Max: 160

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - '**/*spec.rb'

Style/Alias:
  Enabled: false # allow alias or alias_method

Style/Documentation:
  Enabled: false  # true requires documentation at the start of class or module

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$qe_frame]

Style/StringLiterals:
  Enabled: false  # See recent test in http://viget.com/extend/just-use-double-quoted-ruby-strings

Style/WordArray:
  MinSize: 4

Style/SignalException:
  Enabled: false # Quit complaining about raise.

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma # trailing comma reduces the number of commit changes when adding to a list
