name:                lqpl-spec
version:             0.9.2
stability:           Experimental
synopsis:            Compiler and Emulator for Linear-QPL
description:         A command-line compiler, a server based compiler and a server based emulator for Linear-QPL. LQPL is a functional quantum programming language that allows experimenting with and visualizing the effects of quantum algorithms.
tested-with:         GHC
license:             BSD3
license-file:        LICENCE
author:              Brett Giles, Robin Cockett
maintainer:          brett.giles@ucalgary.ca
bug-reports:         mailto:brett.giles@ucalgary.ca
homepage:            http://pll.cpsc.ucalgary.ca/lqpl
build-type:          Simple

tests:
  spec:
   main:          Spec.hs
   dependencies:
     - aeson
     - base
     - bytestring
     - containers
     - directory
     - filepath
     - hspec
     - hspec-contrib
     - hspec-core
     - HUnit
     - lqpl-common
     - lqpl-compiler
     - lqpl-compiler-server
     - lqpl-emulator
     - mtl
     - network
     - parsec
     - process
     - QuickCheck
     - unix
   source-dirs:
     - hspec
   build-tools: hspec-discover
