source 'http://rubygems.org'
source 'http://gems.neurogami.com'

gem 'rake'
gem 'monkeybars', '~>1.1'

group :test, :development do
  gem "rspec", '~> 3.0.0.beta'
  gem "cucumber"
  gem 'simplecov'
  gem 'flog'
  gem 'flay'
  gem 'syntax'
  gem 'awesome_print'
  gem 'rubocop'
  gem 'coderay'


  gem 'rspec-formatter-webkit'
  gem 'fuubar'  # rspec formatter
  #gem 'rspec_junit_formatter'
end

