source 'http://rubygems.org'
source 'http://gems.neurogami.com'

gem 'rake'
gem 'monkeybars', '~>1.1'

group :test, :development do
  gem "rspec"
  gem "cucumber"
  gem 'simplecov'
  gem 'flog'
  gem 'flay'
  gem 'syntax'
  gem 'awesome_print'
  gem 'rubocop'
end

